version: "3"

services:
  #web:
  #  build: ./paperless-ngx-ui
  #  ports:
  #    - "80:80"
        
  api:
    build:
      dockerfile: ./Org.OpenAPITools/Dockerfile
      context: .
      args:
        BUILD_CONFIG: Release #Debug
    depends_on:
      - db
      - minio
      - rabbitmq
      - elasticsearch
    ports:
      - "8000:80"

    
  
  db:
    image: docker.io/library/postgres:15
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ACCESS_KEY: fatimatuana
      MINIO_SECRET_KEY: fatimatuana
    command: server --console-address ":9001" /data

  rabbitmq:
    image: rabbitmq:management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: paperless
      RABBITMQ_DEFAULT_PASS: paperless


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    restart: unless-stopped
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

        
  ocr_worker:
    build:
      dockerfile: ./PaperlessWorkerService/Dockerfile
      context: .
      args:
        BUILD_CONFIG: Release #Debug
    depends_on:
      - elasticsearch
      - rabbitmq
      - minio
    environment:
      - ENVIRONMENT=docker

  
volumes:
  postgres_data:
  rabbitmq_data:
  minio_data:
  elasticsearch_data: